spring.application.name=semumreal

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
app.google.client-ids=${APP_GOOGLE_CLIENT_IDS:}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:8081,http://127.0.0.1:8081,http://localhost:8181,http://127.0.0.1:8181,http://localhost:4200,http://127.0.0.1:4200}

springdoc.swagger-ui.persistAuthorization=true
